// Mock data for Implementos
const CATEGORIES = [
  { id: 'lubricantes', name: 'Lubricantes y fluidos', count: 1284, icon: 'oil' },
  { id: 'frenos', name: 'Sistema de frenos', count: 892, icon: 'brake' },
  { id: 'filtros', name: 'Filtros', count: 543, icon: 'filter' },
  { id: 'baterias', name: 'Baterías', count: 187, icon: 'battery' },
  { id: 'neumaticos', name: 'Neumáticos', count: 412, icon: 'tire' },
  { id: 'suspension', name: 'Suspensión', count: 678, icon: 'shock' },
  { id: 'motor', name: 'Motor', count: 1521, icon: 'engine' },
  { id: 'electrico', name: 'Sistema eléctrico', count: 765, icon: 'spark' },
  { id: 'transmision', name: 'Transmisión', count: 398, icon: 'gear' },
  { id: 'herramientas', name: 'Herramientas', count: 1102, icon: 'wrench' },
  { id: 'seguridad', name: 'Implementos seguridad', count: 287, icon: 'shield' },
  { id: 'accesorios', name: 'Accesorios y tuning', count: 654, icon: 'star' },
];

const BRANDS = [
  'Bosch', 'Mann-Filter', 'Castrol', 'Shell', 'Mobil', 'Valvoline',
  'Brembo', 'TRW', 'Continental', 'Michelin', 'Bridgestone', 'Goodyear',
  'Varta', 'Exide', 'NGK', 'Denso', 'Sachs', 'Monroe', 'Bilstein', 'KYB'
];

const PRODUCTS = [
  {
    id: 'p001',
    sku: 'BSC-0986452041',
    name: 'Filtro de aceite Bosch P7041',
    brand: 'Bosch',
    category: 'filtros',
    price: 12990,
    listPrice: 16490,
    stock: 47,
    rating: 4.7,
    reviews: 128,
    badge: 'OEM',
    fitsVehicle: true,
    image: 'filter',
    description: 'Filtro de aceite premium para motores diésel pesados. Compatible con flotas Mercedes-Benz, Volvo y Scania.',
  },
  {
    id: 'p002',
    sku: 'CAS-15W40-208',
    name: 'Aceite Castrol Vecton 15W-40 — Tambor 208L',
    brand: 'Castrol',
    category: 'lubricantes',
    price: 1289000,
    listPrice: 1450000,
    stock: 12,
    rating: 4.9,
    reviews: 87,
    badge: 'Más vendido',
    fitsVehicle: true,
    image: 'oil-drum',
    description: 'Aceite mineral premium para motores diésel de servicio pesado. Intervalo extendido de cambio.',
  },
  {
    id: 'p003',
    sku: 'BRB-P85020',
    name: 'Pastillas de freno Brembo P85020 (kit x4)',
    brand: 'Brembo',
    category: 'frenos',
    price: 89900,
    listPrice: 109900,
    stock: 23,
    rating: 4.8,
    reviews: 245,
    badge: 'Premium',
    fitsVehicle: true,
    image: 'brake',
    description: 'Pastillas cerámicas de alto rendimiento. Bajo desgaste, sin polvo, frenado consistente.',
  },
  {
    id: 'p004',
    sku: 'VAR-625-13',
    name: 'Batería Varta Promotive 180Ah 1000A',
    brand: 'Varta',
    category: 'baterias',
    price: 245000,
    listPrice: 289000,
    stock: 8,
    rating: 4.6,
    reviews: 56,
    fitsVehicle: false,
    image: 'battery',
    description: 'Batería de arranque para camiones de servicio pesado. Tecnología EFB.',
  },
  {
    id: 'p005',
    sku: 'MIC-XZE2-315',
    name: 'Neumático Michelin XZE2+ 315/80R22.5',
    brand: 'Michelin',
    category: 'neumaticos',
    price: 489000,
    listPrice: 549000,
    stock: 34,
    rating: 4.9,
    reviews: 312,
    badge: 'Top',
    fitsVehicle: true,
    image: 'tire',
    description: 'Neumático regional para uso urbano e interurbano. Larga duración y agarre superior.',
  },
  {
    id: 'p006',
    sku: 'MAN-W940-25',
    name: 'Filtro de combustible Mann W 940/25',
    brand: 'Mann-Filter',
    category: 'filtros',
    price: 18900,
    listPrice: 22900,
    stock: 156,
    rating: 4.7,
    reviews: 89,
    fitsVehicle: true,
    image: 'fuel-filter',
    description: 'Separador agua-combustible. Original equipment para Volvo y MAN.',
  },
  {
    id: 'p007',
    sku: 'SAC-3151-145',
    name: 'Amortiguador Sachs 313 145 (par)',
    brand: 'Sachs',
    category: 'suspension',
    price: 78500,
    listPrice: 95000,
    stock: 28,
    rating: 4.5,
    reviews: 64,
    fitsVehicle: false,
    image: 'shock',
    description: 'Amortiguador trasero para tracto-camiones. Tecnología Twin-Tube.',
  },
  {
    id: 'p008',
    sku: 'NGK-DCPR8E',
    name: 'Bujías NGK DCPR8E (kit x6)',
    brand: 'NGK',
    category: 'electrico',
    price: 24900,
    listPrice: 32000,
    stock: 89,
    rating: 4.8,
    reviews: 198,
    fitsVehicle: true,
    image: 'spark',
    description: 'Bujías de iridio. Mayor duración y mejor combustión.',
  },
  {
    id: 'p009',
    sku: 'SHL-RIM-10W40',
    name: 'Shell Rimula R6 LME 10W-40 — Bidón 20L',
    brand: 'Shell',
    category: 'lubricantes',
    price: 198000,
    listPrice: 229000,
    stock: 41,
    rating: 4.8,
    reviews: 142,
    badge: 'Eco',
    fitsVehicle: true,
    image: 'oil',
    description: 'Aceite sintético premium para motores Euro V/VI. Bajo consumo de combustible.',
  },
  {
    id: 'p010',
    sku: 'CON-MFR-22.5',
    name: 'Manguera radiador Continental MFR-22 — 1.5m',
    brand: 'Continental',
    category: 'motor',
    price: 34900,
    listPrice: 42000,
    stock: 17,
    rating: 4.4,
    reviews: 31,
    fitsVehicle: false,
    image: 'hose',
    description: 'Manguera reforzada de silicona. Resistente a 180°C.',
  },
  {
    id: 'p011',
    sku: 'TRW-GDB1330',
    name: 'Disco freno TRW DF4187',
    brand: 'TRW',
    category: 'frenos',
    price: 67800,
    listPrice: 79900,
    stock: 19,
    rating: 4.6,
    reviews: 73,
    fitsVehicle: true,
    image: 'disc',
    description: 'Disco ventilado, recubrimiento anti-óxido. Diámetro 432mm.',
  },
  {
    id: 'p012',
    sku: 'BSC-AERO-26',
    name: 'Plumillas Bosch Aerotwin 26"+18" (par)',
    brand: 'Bosch',
    category: 'accesorios',
    price: 19900,
    listPrice: 27000,
    stock: 234,
    rating: 4.7,
    reviews: 412,
    fitsVehicle: true,
    image: 'wiper',
    description: 'Plumillas planas de alto rendimiento. Sistema de adaptación universal.',
  },
];

const VEHICLE_BRANDS = ['Mercedes-Benz', 'Volvo', 'Scania', 'MAN', 'Iveco', 'DAF', 'Renault Trucks', 'Ford Cargo', 'Hino', 'Isuzu', 'Mitsubishi Fuso', 'International'];
const VEHICLE_MODELS = {
  'Mercedes-Benz': ['Actros 1844', 'Actros 2545', 'Atego 1726', 'Axor 2536', 'Sprinter 415'],
  'Volvo': ['FH 460', 'FH 540', 'FM 420', 'VM 270', 'FMX 500'],
  'Scania': ['R 450', 'R 500', 'G 410', 'P 280', 'S 730'],
  'MAN': ['TGX 28.480', 'TGS 33.440', 'TGM 18.290'],
  'Iveco': ['Stralis 460', 'Daily 70C17', 'Tector 170E22'],
  'DAF': ['XF 480', 'CF 410', 'LF 230'],
  'Renault Trucks': ['T 460', 'C 380', 'D Wide'],
  'Ford Cargo': ['1932', '2842', '816'],
  'Hino': ['500 1726', '700 SS'],
  'Isuzu': ['NPR 75', 'FRR 90', 'GIGA'],
  'Mitsubishi Fuso': ['Canter 815', 'Fighter FM'],
  'International': ['9800i', 'Durastar', 'WorkStar'],
};
const VEHICLE_YEARS = Array.from({ length: 26 }, (_, i) => 2025 - i);

const SAVED_VEHICLES = [
  { id: 'v1', brand: 'Mercedes-Benz', model: 'Actros 1844', year: 2021, plate: 'KZBF-22', km: 287400, alias: 'Tracto principal' },
  { id: 'v2', brand: 'Volvo', model: 'FH 460', year: 2019, plate: 'JCDR-91', km: 612000, alias: 'Volvo flota' },
  { id: 'v3', brand: 'Scania', model: 'R 500', year: 2023, plate: 'PVHS-04', km: 89000, alias: 'Scania nuevo' },
];

const ORDERS = [
  { id: 'IMP-2026-04812', date: '2026-04-22', status: 'En tránsito', items: 4, total: 387900, eta: '2026-04-28' },
  { id: 'IMP-2026-04567', date: '2026-04-12', status: 'Entregado', items: 2, total: 134800, eta: '2026-04-15' },
  { id: 'IMP-2026-04201', date: '2026-03-28', status: 'Entregado', items: 7, total: 1287400, eta: '2026-04-01' },
  { id: 'IMP-2026-03987', date: '2026-03-15', status: 'Entregado', items: 1, total: 89900, eta: '2026-03-17' },
];

const STORES = [
  { id: 'stgo-centro', name: 'Santiago Centro', address: 'San Diego 1247, Santiago', region: 'RM', stockHealth: 0.94, eta: 'Hoy antes 18h', isFlagship: true },
  { id: 'stgo-providencia', name: 'Providencia', address: 'Av. Providencia 2580', region: 'RM', stockHealth: 0.88, eta: 'Hoy antes 18h' },
  { id: 'stgo-quilicura', name: 'Quilicura', address: 'Av. Lo Marcoleta 0680', region: 'RM', stockHealth: 0.97, eta: 'Hoy antes 20h', isWarehouse: true },
  { id: 'stgo-maipu', name: 'Maipú', address: 'Av. Pajaritos 4910', region: 'RM', stockHealth: 0.82, eta: 'Mañana antes 14h' },
  { id: 'stgo-puente-alto', name: 'Puente Alto', address: 'Av. Concha y Toro 3100', region: 'RM', stockHealth: 0.79, eta: 'Mañana antes 14h' },
  { id: 'valpo', name: 'Valparaíso', address: 'Av. España 1680, Viña del Mar', region: 'V', stockHealth: 0.71, eta: 'Mañana antes 18h' },
  { id: 'concepcion', name: 'Concepción', address: 'Av. Jorge Alessandri 3177', region: 'VIII', stockHealth: 0.74, eta: 'Mañana antes 18h' },
  { id: 'temuco', name: 'Temuco', address: 'Av. Pedro de Valdivia 990', region: 'IX', stockHealth: 0.66, eta: '2 días hábiles' },
  { id: 'antofagasta', name: 'Antofagasta', address: 'Av. Edmundo Pérez Zujovic 11500', region: 'II', stockHealth: 0.68, eta: '2 días hábiles' },
  { id: 'la-serena', name: 'La Serena', address: 'Ruta 5 Norte Km 471', region: 'IV', stockHealth: 0.62, eta: '2 días hábiles' },
  { id: 'rancagua', name: 'Rancagua', address: 'Av. Miguel Ramírez 0750', region: 'VI', stockHealth: 0.70, eta: 'Mañana antes 20h' },
  { id: 'puerto-montt', name: 'Puerto Montt', address: 'Av. Presidente Ibáñez 800', region: 'X', stockHealth: 0.58, eta: '3 días hábiles' },
];

// Volume pricing — derived from base price.
// Returns array of tiers: { min, max, price, discount } where price is unit price at that volume.
// Items priced over $200K (drums, baterías, neumáticos) use smaller tiers (1, 2, 4, 8+).
// Cheap items (filtros, accesorios) use larger ranges (1, 4, 12, 24+).
const computeVolumeTiers = (product) => {
  if (!product) return null;
  const expensive = product.price >= 200000;
  const ranges = expensive
    ? [{ min: 1, max: 1 }, { min: 2, max: 3 }, { min: 4, max: 7 }, { min: 8, max: null }]
    : [{ min: 1, max: 3 }, { min: 4, max: 11 }, { min: 12, max: 23 }, { min: 24, max: null }];
  const discounts = [0, 0.05, 0.10, 0.15];
  return ranges.map((r, i) => ({
    ...r,
    discount: discounts[i],
    price: Math.round(product.price * (1 - discounts[i])),
  }));
};

window.MOCK = { CATEGORIES, BRANDS, PRODUCTS, VEHICLE_BRANDS, VEHICLE_MODELS, VEHICLE_YEARS, SAVED_VEHICLES, ORDERS, STORES, computeVolumeTiers };
